### ISSUE TITLE
About the elapsed seconds printed

### ISSUE THREAD

**Issue by BruceZoom** [xushangning/ei338#1]
The book says "report the number of seconds that have elapsed since __the__ kernel module was first loaded".  The time interval to be printed seems to be the time from __the loading of this "seconds" kernel__.

By the way, how to print more accurate time using float? It seems using float cause some errors: "SSE register return with SSE disabled".

**Comment by xushangning** [comment]
You are correct. Now I have to come back and fix my code...

For the second point, this [StackOverflow answer](https://stackoverflow.com/questions/13886338/use-of-floating-point-in-the-linux-kernel) offers an explanation.

**Comment by BruceZoom** [comment]
Thanks for the answer. So, there is no way (no need) to improve the accuracy with float.

**Comment by xushangning** [comment]
Actually you can, if you are willing to write your own floating-point subroutine.:cry:
